/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarea_2;

import java.util.Arrays;

public class App {

    private int[] array;

    /**
     * 
     * @param array Este array definirá el contenido del array
     */
    public App(int[] array) {
        this.array = array;
    }

    // public int contarElements() throws Exception {
    public int contarElements() {
        if (array != null) {
            return array.length;
        } else {
            return 0;
        }
        // throw new Exception("Error: el array es nulo");
    }

    /**
     * Esta funcion hace esto esto y aquello.
     * 
     * @return entero con el valor del primer elemento. Si el array es vacio o nulo,
     *         pasará esto.
     */
    public int devolPrimero() throws Exception {
        if (array == null || array.length == 0)
            throw new Exception("Error: el array es nulo");
        return array[0];
    }

    public int devolUltimo() throws Exception {
        if (array == null || array.length == 0)
            throw new Exception("Error: el array es nulo");
        return array[array.length - 1];
    }

    public int devolTercero() throws Exception {
        if (array == null || array.length == 0 || array.length < 3)
            throw new Exception("Error: el array es nulo");
        return array[2];
    }

    public int sumaElements() throws Exception {
        if (array == null || array.length == 0)
            throw new Exception("Error: el array es nulo");
        return Arrays.stream(array).sum();
    }

    public double mediaElements() throws Exception {
        if (array == null || array.length == 0)
            throw new Exception("Error: el array es nulo");
        return Arrays.stream(array).average().getAsDouble();
    }
}
