/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarea_1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Me llamo Juan Antonio Kumar Corbas alias Toñin");
    }
}
